restaurant:
  info:
    name: "Restaurant Dev"
    description: "Restaurant API"
    version: "1.0.0"

server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant
    username: sarandy
    password: 123
    driver-class-name: org.postgresql.Driver