business:
  info:
    name: "Business Dev"
    description: "Business API"
    version: "1.0.0"

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc/postgresql://localhost:5432/db_name
    username: postgres
    password: Vsarandy
    driver-class-name: org.postgresql.Driver