business:
  info:
    name: "Business Dev"
    description: "Business API"
    version: "1.0.0"

server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/devOps
    username: postgres
    password: Vsarandy
    driver-class-name: org.postgresql.Driver