identity:
  info:
    name: "Identity Dev"
    description: "Identity API"
    version: "1.0.0"

server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://34.101.79.242:5430/oauth2
    username: sarandy
    password: 123
    driver-class-name: org.postgresql.Driver