user-profile:
  info:
    name: "User-profile Dev"
    description: "User-profile API"
    version: "1.0.0"

server:
  port: 8086

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://34.101.79.242:5431/user-profile
    username: sarandy
    password: 123
    driver-class-name: org.postgresql.Driver