product:
  info:
    name: "Product Dev"
    description: "Product API"
    version: "1.0.0"

server:
  port: 8083

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://34.101.79.242:5431/product
    username: sarandy
    password: 123
    driver-class-name: org.postgresql.Driver